### PR TITLE
Develop

### LINKED ISSUE #21: Acceptance test sdk operation type not match
### Bug description

We get error in updating acceptance test  Test_Source_Read_Success_cdc
https://github.com/ConduitIO/conduit-connector-sdk/blob/main/acceptance_testing.go#L719 .
Erorr is :  record operation did not match
It is because Snowflake combined iterator switch to CDC iterator when snapshot iterator doesn't return record (method hasNext return false).
In this test  test driver write more data while connector is running.
https://github.com/ConduitIO/conduit-connector-sdk/blob/main/acceptance_testing.go#L715
Snowflake sets  record type operation OperationSnapshot for this records but test is waiting for type OperationCreate ,

### Steps to reproduce

1. Run acceptance test
2. See results

### Version

v0.4.0-nightly.20221028-dirty

### PR DESCRIPTION
**Pull request by maksenius**
Fixes #21 , #22 

Fix problem with huge tables.
Change snapshot logic, add snapshot max value logic.

### Quick checks:

- [x] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [x] There is no other [pull request](https://github.com/conduitio-labs/conduit-connector-snowflake/pulls) for the same update/change.
- [x] I have written unit tests.
- [x] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: repository/snowflake.go [hunk 1]
```diff
@@ -229,20 +220,46 @@ func (s *Snowflake) GetTrackingData(
...
 
-	if len(fields) == 0 {
-		sb.Select("*")
-	} else {
-		sb.Select(fields...)
+	return rows.Next(), nil
+}
+
+// IsStreamExist check if stream exist.
+func (s *Snowflake) IsStreamExist(ctx context.Context, stream string) (bool, error) {
```
Comment (hariso) [inline repository/snowflake.go:235]: I'd suggest `StreamExists` or something similar (IsStreamExist isn't quite correct grammatically).

File: repository/snowflake.go [hunk 2]
```diff
@@ -229,20 +220,46 @@ func (s *Snowflake) GetTrackingData(
 	return result, nil
 }
 
-func buildGetDataQuery(table, key string, fields []string, offset, limit int) string {
-	sb := sqlbuilder.NewSelectBuilder()
+// IsTableExist check if table exist.
+func (s *Snowflake) IsTableExist(ctx context.Context, table string) (bool, error) {
```
Comment (hariso) [inline repository/snowflake.go:224]: I'd suggest `TableExists` or something similar (IsTableExist isn't quite correct grammatically).

File: source/iterator/cdc.go [hunk 3]
```diff
@@ -96,6 +97,17 @@ func (c *CDCIterator) HasNext(ctx context.Context) (bool, error) {
 	c.currentBatch, err = c.snowflake.GetTrackingData(ctx, getStreamName(c.table),
 		getTrackingTable(c.table), c.columns, c.offset, c.batchSize)
 	if err != nil {
+		// Snowflake library sends request to abort query with query and to server when get context cancel.
+		// But sometimes query was executed or didn't start execution.
+		// On this case snowflake server return specific error:
+		// 000605: Identified SQL statement is not currently executing.
+		// Connector can't return this error and connector replace to
+		// context cancel error
+		// https://github.com/snowflakedb/gosnowflake/blob/master/restful.go#L449
```
Comment (hariso) [inline source/iterator/cdc.go:106]: Let me check if I understood this correctly: If the context is canceled, you get this error `000605: Identified SQL statement is not currently executing`? Why does it matter if "sometimes query was executed or didn't start execution"?

File: source/iterator/iterator.go [hunk 4]
```diff
@@ -110,29 +100,36 @@ func New(
...
 
-	if !isFirstStart {
-		index = element + 1
+	if !isTableExist {
+		// Prepare tracking table for consume stream.
+		err = snowflake.CreateTrackingTable(ctx, getTrackingTable(table), table)
+		if err != nil {
+			return fmt.Errorf("create tracking table: %w", err)
+		}
 	}
```
Comment (hariso) [inline source/iterator/iterator.go:116]: Is it possible to write "create if not exists"?

File: source/iterator/iterator.go [hunk 5]
```diff
@@ -110,29 +100,36 @@ func New(
...
-		columns, key, index, offset, batchSize, data), nil
+	if !isStreamExist {
+		// Prepare stream for cdc iterator.
+		err = snowflake.CreateStream(ctx, getStreamName(table), table)
+		if err != nil {
+			return fmt.Errorf("create stream: %w", err)
+		}
+	}
+
+	return nil
```
Comment (hariso) [inline source/iterator/iterator.go:132]: Is it possible to write "create stream if not exists"?

File: source/position/position.go [hunk 6]
```diff
@@ -34,43 +35,51 @@ type Position struct {
 	// IteratorType - shows in what iterator was created position.
 	IteratorType IteratorType
 
+	// Snapshot information.
+	// SnapshotLastProcessedVal - last processed value from ordering column.
+	SnapshotLastProcessedVal any
+	// SnapshotMaxValue max value by  ordering column, when snapshot starts work.
+	SnapshotMaxValue any
```
Comment (hariso) [inline source/position/position.go:42]: So, essentially this is what was needed to fix the bug in #22?

File: README.md [hunk 7]
```diff
@@ -34,43 +35,25 @@ Run `make test`.
 ### Snowflake Source
 
 The Snowflake Source Connector connects to a snowflake with the provided configurations, using
-`connection`, `table`,`columns`, `primaryKey`, `batchSize`  and using snowflake driver.
+`connection`, `table`,`columns`, `orderingColumn`, `primaryKey`, `batchSize`  and using snowflake driver.
 Source method `Configure`  parse the configurations.
 `Open` method is called to start the connection from the provided position get the
 data from snowflake db. The `Read` return next record. The `Ack` method
 checks if the record with the position was recorded. The `Teardown` do gracefully shutdown.
```
[the remark this answers is not in the document]
Comment (maksenius) [reply README.md]: ok, I removed it

File: README.md [hunk 8]
```diff
@@ -34,43 +35,25 @@ Run `make test`.
...
 
 #### Snapshot Iterator
```
[the remark this answers is not in the document]
Comment (maksenius) [reply README.md:37]: yeah, good idea.
I added general info

File: README.md [hunk 9]
```diff
@@ -150,14 +133,17 @@ Connectors will transform this data to records.
...
 Example:
 
 ```json
 {
  "Type" : "c",
+ "SnapshotLastProcessedVal" : 299,
+ "SnapshotMaxValue" : 299,
  "IndexInBatch": 2,
  "BatchID": 5
 }
```
[the remark this answers is not in the document]
Comment (maksenius) [reply README.md]: sure, done

File: acceptance_test.go [hunk 10]
```diff
@@ -33,13 +34,15 @@ import (
 	"github.com/conduitio-labs/conduit-connector-snowflake/source/iterator"
 )
 
-// ConfigurableAcceptanceTestDriver driver for test.
-type ConfigurableAcceptanceTestDriver struct {
+// driver Configurable Acceptance test driver.
+type driver struct {
 	sdk.ConfigurableAcceptanceTestDriver
+
+	counter int32
```
[the remark this answers is not in the document]
Comment (maksenius) [reply acceptance_test.go:41]: Yes  you are right

File: config/config.go [hunk 11]
```diff
@@ -16,18 +16,32 @@ package config
...
 
-	defaultBatchSize = 1000
+	// KeyBatchSize is a config name for a batch size.
+	KeyBatchSize = "batchSize"
+
+	// KeyOrderingColumn is a config name for an ordering column.
+	KeyOrderingColumn = "orderingColumn"
+
+	// defaultBatchSize is a default value for a BatchSize field.
+	defaultBatchSize = 100
```
[the remark this answers is not in the document]
Comment (maksenius) [reply config/config.go]: When I have investigated issue I set 100 but now after fix we can return to 1000

[the remark this answers is not in the document]
Comment (maksenius) [reply config/config.go]: I have returned

File: config/config_test.go [hunk 12]
```diff
@@ -30,68 +30,87 @@ func TestParse(t *testing.T) {
...
+				Key:            "ID",
+				BatchSize:      defaultBatchSize,
+				OrderingColumn: "ID",
 			},
 			wantErr:     false,
 			expectedErr: "",
 		},
 		{
-			name: "missing connection field",
+			name: "missed connection field",
```
[the remark this answers is not in the document]
Comment (maksenius) [reply config/config_test.go]: ok, I have returned previous variant

File: repository/snowflake.go [hunk 13]
```diff
@@ -16,42 +16,44 @@ package repository
...
 import (
 	"context"
-	"database/sql"
 	"fmt"
+	"reflect"
 	"strings"
-	"time"
 
 	"github.com/huandu/go-sqlbuilder"
+	"github.com/jmoiron/sqlx"
```
[the remark this answers is not in the document]
Comment (maksenius) [reply repository/snowflake.go:24]: Because we are using method  MapScan from sqlx lib
```
// MapScan using this Rows.
func (r *Rows) MapScan(dest map[string]interface{}) error {
	return MapScan(r, dest)
}
```
For example on line https://github.com/conduitio-labs/conduit-connector-snowflake/blob/develop/source/iterator/snapshot.go#L142

File: source/iterator/snapshot_test.go [hunk 14]
```diff
@@ -1,233 +0,0 @@
-// Copyright © 2022 Meroxa, Inc.
```
[the remark this answers is not in the document]
Comment (maksenius) [reply source/iterator/snapshot_test.go]: returned tests  to this file

File: source/iterator/snapshot.go [hunk 15]
```diff
@@ -37,97 +41,151 @@ type SnapshotIterator struct {
...
+		if err != nil {
+			return nil, fmt.Errorf("get max value: %w", err)
+		}
+	} else {
+		snapshotIterator.maxValue = position.SnapshotMaxValue
+	}
+
+	snapshotIterator.rows, err = snapshotIterator.snowflake.GetRows(ctx, table, orderingColumn, columns,
+		position, snapshotIterator.maxValue, batchSize)
+	if err != nil {
```
[the remark this answers is not in the document]
Comment (maksenius) [reply source/iterator/snapshot.go:88]: Yes. We create new snapshot iterator  inside  source `open` method and we want to get first batch of data. Inside `HasNext` method we first check if we have data and only after that call GetRows method

File: repository/snowflake.go (hunk 2 above)
Comment (maksenius) [reply repository/snowflake.go]: changed

File: repository/snowflake.go (hunk 1 above)
Comment (maksenius) [reply repository/snowflake.go]: changed

File: source/iterator/snapshot.go [hunk 16]
```diff
@@ -37,97 +41,151 @@ type SnapshotIterator struct {
...
-		batchSize:    batchSize,
-		currentBatch: currentBatch,
+	batchSize int,
+	position *position.Position,
+) (*SnapshotIterator, error) {
+	var (
+		err error
+	)
+
+	snapshotIterator := &SnapshotIterator{
```
[the remark this answers is not in the document]
Comment (maksenius) [reply source/iterator/snapshot.go]: yep, agree. Done

File: source/iterator/snapshot.go [hunk 17]
```diff
@@ -37,97 +41,151 @@ type SnapshotIterator struct {
...
+	// orderingColumn Name of column what iterator using for sorting data.
+	orderingColumn string
+	// position last recorded position.
+	position *position.Position
+	// maxValue max value by ordering column when snapshot starts works
+	maxValue any
 }
 
-// NewSnapshotIterator iterator.
+// NewSnapshotIterator new snapshot iterator.
```
[the remark this answers is not in the document]
Comment (maksenius) [reply source/iterator/snapshot.go]: done

File: source/iterator/snapshot.go [hunk 18]
```diff
@@ -18,15 +18,19 @@ import (
...
 	"time"
 
 	sdk "github.com/conduitio/conduit-connector-sdk"
+	"github.com/jmoiron/sqlx"
 
 	"github.com/conduitio-labs/conduit-connector-snowflake/source/position"
 )
 
 // SnapshotIterator to iterate snowflake objects.
 type SnapshotIterator struct {
```
[the remark this answers is not in the document]
Comment (maksenius) [reply source/iterator/snapshot.go]: no,
I fixed it

File: source/iterator/snapshot.go [hunk 19]
```diff
@@ -37,97 +41,151 @@ type SnapshotIterator struct {
...
 
-	payload, err = json.Marshal(i.currentBatch[i.index])
+	pos := position.Position{
+		IteratorType:             position.TypeSnapshot,
+		SnapshotLastProcessedVal: row[i.orderingColumn],
+		SnapshotMaxValue:         i.maxValue,
+		Time:                     time.Now(),
+	}
+
+	convertedPosition, err := pos.ConvertToSDKPosition()
```
[the remark this answers is not in the document]
Comment (maksenius) [reply source/iterator/snapshot.go]: ok
I changed it

File: source/iterator/cdc.go (hunk 3 above)
Comment (maksenius) [reply source/iterator/cdc.go:106]: I want to add information why  we get this error, but if you think it is redundant , we can remove it

File: source/iterator/iterator.go (hunk 4 above)
Comment (maksenius) [reply source/iterator/iterator.go]: let me recheck docs

File: source/iterator/iterator.go (hunk 5 above)
Comment (maksenius) [reply source/iterator/iterator.go:132]: let me recheck docs

File: source/position/position.go (hunk 6 above)
Comment (maksenius) [reply source/position/position.go:42]: Yes  and also it resolve issue with acceptance test

File: source/iterator/iterator.go (hunk 4 above)
Comment (maksenius) [reply source/iterator/iterator.go]: Yeah, but as for me better to check if table exist, because we add to this table additional fields and when  we start connectors and use query ```create table if exist```  we can't know if table  is exist and we don't do we need add new fields (it is can be case when created snowflake connector (tracking table was created), removed it and created one more time the same source connector)

File: source/iterator/iterator.go (hunk 5 above)
Comment (maksenius) [reply source/iterator/iterator.go:132]: let me recheck it

Comment (maksenius) [reply source/iterator/iterator.go]: yeah we can, I did it and removed not needed method

File: repository/snowflake.go (hunk 1 above)
Comment (maksenius) [reply repository/snowflake.go]: we don't need to have this method, it was removed

File: repository/const.go [hunk 20]
```diff
@@ -20,11 +20,13 @@ const (
 	MetadataColumnRow    = "METADATA$ROW_ID"
 	MetadataColumnTime   = "METADATA$TS"
 
-	queryCreateStream        = `CREATE OR REPLACE STREAM %s on table %s`
-	queryCreateTrackingTable = `CREATE OR REPLACE TABLE %s LIKE %s`
+	queryCreateStream        = `CREATE STREAM IF NOT EXISTS %s on table %s`
+	queryCreateTrackingTable = `CREATE TABLE %s LIKE %s`
```
Comment (hariso) [inline repository/const.go:24]: Can we add "IF NOT EXISTS" here too?

Comment (maksenius) [reply repository/const.go]: yep, done

File: source/iterator/snapshot.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (hariso) [reply source/iterator/snapshot.go]: Can we do that in HasNext only? A connector's Open() method is meant to merely establish connections, if needed, and not load any data.

File: acceptance_test.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (hariso) [reply acceptance_test.go:41]: Nitpick: It would be nice if we name it so that it's clear it's a record counter or that it's used for record IDs.

File: source/iterator/cdc.go (hunk 3 above)
Comment (maksenius) [reply source/iterator/cdc.go:106]: Yes we will know, snowflake library return this error only inside cancelQuery function
https://github.com/snowflakedb/gosnowflake/blob/master/restful.go#L412
https://github.com/snowflakedb/gosnowflake/blob/master/restful.go#L30

CancelQuery executes only if we have context cancel or context deadline errors
https://github.com/snowflakedb/gosnowflake/blob/master/restful.go#L182

File: source/iterator/snapshot.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (maksenius) [reply source/iterator/snapshot.go]: yes, I removed it

File: acceptance_test.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (maksenius) [reply acceptance_test.go]: ok, I changed name

File: source/iterator/cdc.go (hunk 3 above)
Comment (hariso) [reply source/iterator/cdc.go]: Thanks for that! In that case, it might make sense to extract this code into a single function, which we can call from multiple places (because it's always the same behavior).

**Review by hariso — APPROVED** [review]
